### ISSUE TITLE
Pull in individual highlights

### ISSUE THREAD

**Issue by erauner12** [mtopping/obsidian-raindrop#3]
This plugin is awesome. I know highlights are fairly new. Was going to see if it was on your radar to pull this data as well. Thanks!

**Comment by erauner12** [comment]
In terms of implementation. Would be awesome if with the planned functionality that you have to create pages off of the links. If when you created that page. It pulled in the highlights/notes on each highlight.

**Comment by mtopping** [comment]
@erauner12 I'm going to look into this, but add a couple of quick obvious improvements for the next release. I'm open to any suggestions for the most useful way to implement them and may ask some questions here. I haven't used them myself...yet.

**Comment by iroQuai** [comment]
Syncing highlights to bookmark-notes would be awesome! especially if the template could be edited so it could be customized to ones needs

(The fleeting notes sync plugin does this fairly well)

**Comment by kaiiiz** [comment]
Hi all, just for someone who drastically needs the highlights/annotations pulling features.

Since this plugin seems to be developed in slow progress, I decided to create a new plugin [Raindrop Highlights](https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin) according to my needs, and it's publicly available now. The main goal is to automatically pull the highlights/annotations from Raindrop to Obsidian.

Most of the features are ported from [Hypothesis Plugin](https://github.com/weichenw/obsidian-hypothesis-plugin) like template and auto-sync. Some Raindrop unique features such as collection sync management and nested collections are also implemented as well.

Please give it a try if you're interested in these features. Thanks!

NOTE: This plugin is currently not available on the Obsidian Community Plugin page, the only way to install it is using [manual installation](https://github.com/obsidianmd/obsidian-sample-plugin#manually-installing-the-plugin).
